name: 'Compile and deploy'
inputs:
  host:
    description: 'SSH Host'
  user:
    description: 'SSH Username'
  password:
    description: 'SSH Password'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.host }}
    - ${{ inputs.user }}
    - ${{ inputs.password }}
